<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
    $users = [
        [   
            'fullname' => 'Alice Johnson',
            'national_id' => 'ID12345601',
            'phone' => '555-0001',
            'country' => 'USA',
            'city' => 'New York',
            'email' => 'alice.johnson@example.com',
            'profile_photo' => null,
            'id_photo' => null,
            'work_location' => 'Manhattan',
            'home_location' => 'Brooklyn',
            'gender' => 'female',
            'payment_preference' => 'cash',
            'is_activated' => true,
            'badge' => 'red',
            'password' => bcrypt('password123'),
            'remember_token' => null,
        ],
        [
            'fullname' => 'Bob Smith',
            'national_id' => 'ID12345602',
            'phone' => '555-0002',
            'country' => 'USA',
            'city' => 'Los Angeles',
            'email' => 'bob.smith@example.com',
            'profile_photo' => null,
            'id_photo' => null,
            'work_location' => 'Downtown',
            'home_location' => 'Hollywood',
            'gender' => 'male',
            'payment_preference' => 'cash',
            'is_activated' => true,
            'badge' => 'red',
            'password' => bcrypt('password123'),
            'remember_token' => null,
        ],
        [
            'fullname' => 'Carol Danvers',
            'national_id' => 'ID12345603',
            'phone' => '555-0003',
            'country' => 'USA',
            'city' => 'Chicago',
            'email' => 'carol.danvers@example.com',
            'profile_photo' => null,
            'id_photo' => null,
            'work_location' => 'Loop',
            'home_location' => 'Hyde Park',
            'gender' => 'female',
            'payment_preference' => 'cash',
            'is_activated' => false,
            'badge' => 'red',
            'password' => bcrypt('password123'),
            'remember_token' => null,
        ],
        [
            'fullname' => 'David Wright',
            'national_id' => 'ID12345604',
            'phone' => '555-0004',
            'country' => 'USA',
            'city' => 'Houston',
            'email' => 'david.wright@example.com',
            'profile_photo' => null,
            'id_photo' => null,
            'work_location' => 'Downtown',
            'home_location' => 'Midtown',
            'gender' => 'male',
            'payment_preference' => 'cash',
            'is_activated' => true,
            'badge' => 'red',
            'password' => bcrypt('password123'),
            'remember_token' => null,
        ],
        [
            'fullname' => 'Eve Thompson',
            'national_id' => 'ID12345605',
            'phone' => '555-0005',
            'country' => 'USA',
            'city' => 'Phoenix',
            'email' => 'eve.thompson@example.com',
            'profile_photo' => null,
            'id_photo' => null,
            'work_location' => 'City Center',
            'home_location' => 'Arcadia',
            'gender' => 'female',
            'payment_preference' => 'cash',
            'is_activated' => false,
            'badge' => 'red',
            'password' => bcrypt('password123'),
            'remember_token' => null,
        ],
        [
            'fullname' => 'Frank Lopez',
            'national_id' => 'ID12345606',
            'phone' => '555-0006',
            'country' => 'USA',
            'city' => 'Philadelphia',
            'email' => 'frank.lopez@example.com',
            'profile_photo' => null,
            'id_photo' => null,
            'work_location' => 'Center City',
            'home_location' => 'South Philly',
            'gender' => 'male',
            'payment_preference' => 'cash',
            'is_activated' => true,
            'badge' => 'red',
            'password' => bcrypt('password123'),
            'remember_token' => null,
        ],
        [
            'fullname' => 'Grace Holloway',
            'national_id' => 'ID12345607',
            'phone' => '555-0007',
            'country' => 'USA',
            'city' => 'San Antonio',
            'email' => 'grace.holloway@example.com',
            'profile_photo' => null,
            'id_photo' => null,
            'work_location' => 'Downtown',
            'home_location' => 'Alamo Heights',
            'gender' => 'female',
            'payment_preference' => 'cash',
            'is_activated' => false,
            'badge' => 'red',
            'password' => bcrypt('password123'),
            'remember_token' => null,
        ],
        [
            'fullname' => 'Henry Clark',
            'national_id' => 'ID12345608',
            'phone' => '555-0008',
            'country' => 'USA',
            'city' => 'San Diego',
            'email' => 'henry.clark@example.com',
            'profile_photo' => null,
            'id_photo' => null,
            'work_location' => 'La Jolla',
            'home_location' => 'Pacific Beach',
            'gender' => 'male',
            'payment_preference' => 'cash',
            'is_activated' => true,
            'badge' => 'red',
            'password' => bcrypt('password123'),
            'remember_token' => null,
        ],
        [
            'fullname' => 'Ivy Baker',
            'national_id' => 'ID12345609',
            'phone' => '555-0009',
            'country' => 'USA',
            'city' => 'Dallas',
            'email' => 'ivy.baker@example.com',
            'profile_photo' => null,
            'id_photo' => null,
            'work_location' => 'Downtown',
            'home_location' => 'Lake Highlands',
            'gender' => 'female',
            'payment_preference' => 'cash',
            'is_activated' => false,
            'badge' => 'red',
            'password' => bcrypt('password123'),
            'remember_token' => null,
        ],
        [
            'fullname' => 'Jack Foster',
            'national_id' => 'ID12345610',
            'phone' => '555-0010',
            'country' => 'USA',
            'city' => 'San Jose',
            'email' => 'jack.foster@example.com',
            'profile_photo' => null,
            'id_photo' => null,
            'work_location' => 'Santa Clara',
            'home_location' => 'Willow Glen',
            'gender' => 'male',
            'payment_preference' => 'cash',
            'is_activated' => true,
            'badge' => 'red',
            'password' => bcrypt('password123'),
            'remember_token' => null,
        ],
    ];

    foreach ($users as $user) {
        User::create($user);
    }
    }
}
